// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7KY-PXBAwa0Etw63UBpMIXsFMvKRnHaA',
    appId: '1:533849932596:web:ec55129412e5b29bad1b61',
    messagingSenderId: '533849932596',
    projectId: 'expense-tracker-3b3c3',
    authDomain: 'expense-tracker-3b3c3.firebaseapp.com',
    storageBucket: 'expense-tracker-3b3c3.firebasestorage.app',
    measurementId: 'G-H3GL35MD5D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZcV5CsP0hrxwWx7gaV_Ds1On01_dlbDE',
    appId: '1:533849932596:android:da525591dc8bcc09ad1b61',
    messagingSenderId: '533849932596',
    projectId: 'expense-tracker-3b3c3',
    storageBucket: 'expense-tracker-3b3c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC7Yx00DFmgGoD0Wrdub9kpHRIviEoJxNo',
    appId: '1:533849932596:ios:97567284e0b9a313ad1b61',
    messagingSenderId: '533849932596',
    projectId: 'expense-tracker-3b3c3',
    storageBucket: 'expense-tracker-3b3c3.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC7Yx00DFmgGoD0Wrdub9kpHRIviEoJxNo',
    appId: '1:533849932596:ios:97567284e0b9a313ad1b61',
    messagingSenderId: '533849932596',
    projectId: 'expense-tracker-3b3c3',
    storageBucket: 'expense-tracker-3b3c3.firebasestorage.app',
    iosBundleId: 'com.example.expenseTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7KY-PXBAwa0Etw63UBpMIXsFMvKRnHaA',
    appId: '1:533849932596:web:a5feb456fa28515bad1b61',
    messagingSenderId: '533849932596',
    projectId: 'expense-tracker-3b3c3',
    authDomain: 'expense-tracker-3b3c3.firebaseapp.com',
    storageBucket: 'expense-tracker-3b3c3.firebasestorage.app',
    measurementId: 'G-RJX1065VT0',
  );
}
